security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_API:         ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        in_memory:
            memory:
                users:
                    restapi:  { password: secretpw, roles: [ 'ROLE_API' ] }

    firewalls:
        api:
            pattern:    ^/api
            fos_oauth:  true
            stateless:  true
        oauth_authorize:
            pattern:    ^/oauth/v2/auth
            form_login:
                provider: fos_userbundle
                check_path: /oauth/v2/auth_login_check
                login_path: /oauth/v2/auth_login
            anonymous: true
        oauth_token:
            pattern:    ^/oauth/v2/token
            security:   false
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:         
            pattern: ^/rest
            anonymous: ~
            form_login: false            
            provider: fos_user_bundle
            http_basic:
                realm: "Fumble Mania"
                
    access_control:
        - { path: ^/oauth/v2/auth_login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
